name: Deploy the container to ACI & Run it

# Trigger only when the build pipeline succeeds
on:
  workflow_run:
    workflows: ["Build and Push Docker Image"] 
    types:
      - completed
    branches:
      - main

jobs:
  deploy_to_azure:
    name: Deploy Container to Azure
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      # Check out your code so GitHub can see the main.bicep file!
      - name: Check out repository
        uses: actions/checkout@v4
      # Log into Azure
      - name: Azure Login
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Rebuild the cloud infrastructure automatically
      - name: Deploy Infrastructure (Bicep)
        run: |
          az group create --name rg-football-stats --location uksouth --tags "football-stats-environment=dev"
          az deployment group create \
            --resource-group rg-football-stats \
            --template-file main.bicep \
            --parameters sqlAdminUser=dbadmin sqlAdminPassword=${{ secrets.DB_PASSWORD }} myIpAddress=0.0.0.0

      # Convert repository name to lowercase
      - name: Downcase repository name
        run: echo "REPO=${GITHUB_REPOSITORY,,}" >>${GITHUB_ENV}

      # Dynamically find the SQL Server name and save it to the environment!
      - name: Get dynamic SQL Server Name
        run: |
          SERVER_NAME=$(az sql server list --resource-group rg-football-stats --query "[0].name" -o tsv)
          echo "SQL_SERVER=$SERVER_NAME" >> $GITHUB_ENV
          echo "Discovered SQL Server: $SERVER_NAME"

      #  Deploy the Container (Notice DB_SERVER now uses the dynamic variable!)
      - name: Deploy to Azure Container Instances (ACI)
        run: |
          az container create \
            --resource-group rg-football-stats \
            --name aci-football-harvester \
            --image ghcr.io/${{ env.REPO }}:latest \
            --registry-login-server ghcr.io \
            --registry-username ${{ github.actor }} \
            --registry-password ${{ secrets.GH_REGISTRY_PASSWORD }} \
            --restart-policy Never \
            --location uksouth \
            --environment-variables \
                DB_SERVER=${{ env.SQL_SERVER }}.database.windows.net \
                DB_NAME=sqldb-football-stats \
                DB_USER=dbadmin \
            --secure-environment-variables \
                DB_PASS=${{ secrets.DB_PASSWORD }}